_wandb:
    value:
        cli_version: 0.24.2
        e:
            t18ar54ysyr0rhna73trkud4360az8so:
                codePath: src\tune_model.py
                codePathLocal: src\tune_model.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "235408453632"
                        used: "225960251392"
                email: insiya.munawer@gmail.com
                executable: C:\Users\Taha\OneDrive\Desktop\ML_project\myenv\Scripts\python.exe
                host: DESKTOP-2UAHE1E
                memory:
                    total: "8303452160"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\Taha\OneDrive\Desktop\ML_project\src\tune_model.py
                python: CPython 3.12.1
                root: C:\Users\Taha\OneDrive\Desktop\ML_project
                startedAt: "2026-02-15T07:53:18.100637Z"
                writerId: t18ar54ysyr0rhna73trkud4360az8so
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.12.1
            "5": 0.24.2
            "8":
                - 3
            "12": 0.24.2
            "13": windows-amd64
